services:
  db:
    image: postgres:18-alpine
    container_name: db
    ports:
    - "5432:5432"
    env_file: 
    - .env
    # volumes:
    # - db-data:/var/lib/postgresql

  backend:
    build:
      context: ./apps/api
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
    # build:
    #   context: ./apps/web
    # container_name: frontend
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - backend
    # env_file:
    #   - .env


# volumes:
#   db-data: